type Person {
    firstName: String
    lastName:String
}

type Query{
  people: [Person!]
}

type Mutation {
    createPerson: (firstName: String, lastName:String) => Person!
}

schema {
  query: Query
}