input CreatePerson {
  firstName: String
  lastName:String!
}

type Person {
  id: ID!
  firstName: String
  lastName:String
}

type Query{
  people: [Person!]
}

type Mutation {
  createPerson(
    person:CreatePerson!
  ):Person!
  updatePerson(
    id:String!,
    person:CreatePerson!
  ):Person!
  removePerson(
    id:String!
  ):String
}

schema {
  query: Query
  mutation: Mutation
}