export const RELATION_NODE_MAX_FIELDS = 15;
export const RELATION_NODE_MAX_WIDTH = 800;
export const PRINT_PREVIEW_RELATION_NODE_MAX_FIELDS = 150;
export const PRINT_PREVIEW_RELATION_NODE_MAX_WIDTH = 1200;
